config/routes.rb
Rails.application.routes.draw do
 
  
  resources :orders
  resources :orderitems
  resources :carts
  resources :cartitems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :categories do 
      member do
        get :sub
      end
    end
    resources :subcategories do
      
    end
    resources :products do 
      
    end

  end
  root to:"homes#index"

  # put 'admin/products/sub', to:'products#sub'
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
    belongs_to :category
    has_many :products
    mount_uploader :image, ImageUploader
    extend FriendlyId
    friendly_id :name, use: :slugged
end

app/controllers/admin/subcategories_controller.rb
module Admin
    class SubcategoriesController < ApplicationController
      load_and_authorize_resource
        def index
           @subcategories= Subcategory.all
        end

         def new 
          @subcategory = Subcategory.new
          
        end

        def create
          @subcategory = Subcategory.new(subcategory_params)
           if @subcategory.save
             flash[:success] = "Subcategory successfully created"
             redirect_to admin_category_subcategories_path
           else
             flash[:error] = "Something went wrong"
             render 'new'
            end
        end

        def show
            @subcategory = Subcategory.friendly.find(params[:id])
            
        end

        def edit
          @category = Category.friendly.find(params[:category_id])
          @subcategory = Subcategory.friendly.find(params[:id])
        end

        def update
          @category= Category.find(params[:category_id]) 
          @subcategory = Subcategory.friendly.find(params[:id])
           
          if @subcategory.update(subcategory_params)
              flash[:success] = "Subcategory successfully updated"
              redirect_to admin_category_subcategory_path(@subcategory)
            else
              flash[:error] = "Something went wrong"
              render 'new'
            end
        end
       def destroy
        
        @subcategory = Subcategory.find(params[:id])
        if @subcategory.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to admin_category_subcategories_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to admin_category_subcategories_path
        end
       end
       
       private
       def subcategory_params
        params.require(:subcategory).permit(:name, :category_id, :image)

    end
    end 
end 

app/views/admin/subcategories/_form.html.erb
<%= form_for @subcategory, url: admin_subcategories_path, method: :post do|form| %>

  <p> <%= form.label :name %>
          <%= form.text_field :name %>
  </p>
   <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
   </p>
 <p> <%= form.label :category_id %>
   <% @categories= Category.all %>
    <%= form.select :category_id, options_for_select(@categories.all.pluck(:name){ |category|
    [category.name.titleize,category.id] }, 1), {}, { id: 'categories_select'} %> 
    

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/subcategories/_subcategories.html.erb
<option value="<%= subcategory.id %>"><%= subcategory.name.titleize %></option

app/views/admin/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>


<%= form_for @subcategory, url: admin_category_subcategory_path, method: :put do|form| %>
 <%= form.hidden_field :category_id, :value => @category.id %>
   <p> <%= form.label :name %>
          <%= form.text_field :name %>
   </p>
  <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
    </p>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<a href="/admin/categories/<%= params[:category_id]%>/subcategories/<%= @subcategory.id %>">Show </a>

<%= link_to 'Back', admin_category_subcategories_path %>

app/views/admin/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subcategories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
      <td> <%= subcategory.name %> </td>
      <td> <% if subcategory.image_url %>
       <td><%=link_to image_tag(subcategory.image.url()), style="height:30%; width:20%;" %></td>
      <% end %>
    </td>
        <td><a href="/admin/categories/<%= params[:category_id]%>/subcategories/<%= subcategory.id %>">Show </a></td>
        <td><a href="/admin/categories/<%= params[:category_id]%>/subcategories/<%= subcategory.id %>/edit">Edit </a></td>

<tr style="height:20px"> </tr>
 <%
=begin%>
 <td><button class="btn btn-light"><%= link_to 'Destroy', admin_category_subcategory_path(@category,subcategory), method: :delete, data: { confirm: 'Are you sure?' } %></button></td>  
<%
=end%>

      </tr> 

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_admin_category_subcategory_path %>
<%= link_to 'Back', admin_categories_path %>

app/views/admin/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Back', admin_subcategories_path %>

app/views/admin/subcategories/show.html.erb
<div class="container-fluid" style="text-align: middle">
    <h1 style="text-align: middle">Displaying the Subcategory</h1>
<table class="table table-striped" data: {turbo: false}>

    <tr><td> Name:</td>
    <td><%=  @subcategory.name  %></td></tr>

     <tr><td> Images :</td>

 <% if @subcategory.image_url %>
    <td><%=link_to image_tag(@subcategory.image.url()) %></td>
<% end %>
</tr>
</table>
<%= link_to 'Back', admin_category_subcategories_path %> |
<a href="/admin/products/new" >New Product</a>
</div>