config/routes.rb
Rails.application.routes.draw do
 
  
  resources :orders
  resources :orderitems
  resources :carts
  resources :cartitems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :categories do 
      member do
        get :sub
      end
    end
    resources :subcategories do
      
    end
    resources :products do 
      
    end

  end
  root to:"homes#index"

  # put 'admin/products/sub', to:'products#sub'
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  before_action :set_orderitem, only: %i[ show edit update destroy ]

  # GET /orderitems or /orderitems.json
  def index
    @c = current_user.cart
     @orderitems= @c.cartitems
  end

  # GET /orderitems/1 or /orderitems/1.json
  def show
    
  end

  # GET /orderitems/new
  def new
    @orderitem = Orderitem.new
  end

  # GET /orderitems/1/edit
  def edit
  end

  # POST /orderitems or /orderitems.json
  def create
    
    @cartitems= user(current_user).cartitems
     @cartitems.each do|c|
    @orderitem=Orderitem.create(quantity: c.quantity,user_id: current_user.id) 
  end
    
    respond_to do |format|
      if @orderitem.save 
     
        format.html { redirect_to orders_path }
        format.json { render :show, status: :created, location: @orderitem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @orderitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderitems/1 or /orderitems/1.json
  def update
    respond_to do |format|
      if @orderitem.update(orderitem_params)
        format.html { redirect_to orderitem_url(@orderitem), notice: "Orderitem was successfully updated." }
        format.json { render :show, status: :ok, location: @orderitem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @orderitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderitems/1 or /orderitems/1.json
  def destroy
    @orderitem.destroy

    respond_to do |format|
      format.html { redirect_to orderitems_url, notice: "Orderitem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def user(user)
    user.cart
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderitem
      @orderitem = Orderitem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orderitem_params
      params.permit(:orderitem).require(:user_id)
    end
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/views/orderitems/_form.html.erb
<%= form_with(model: orderitem, local: true) do |form| %>
  <% if orderitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orderitem.errors.count, "error") %> prohibited this orderitem from being saved:</h2>

      <ul>
        <% orderitem.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
<%= f.hidden_field :order_id, :value=> current_user.order.id %>
<%  %>
    <%= form.submit %>
  </div>
<% end %>

app/views/orderitems/edit.html.erb
<h1>Editing Orderitem</h1>

<%= render 'form', orderitem: @orderitem %>

<%= link_to 'Show', @orderitem %> |
<%= link_to 'Back', orderitems_path %>

app/views/orderitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orderitems</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orderitems.each do |orderitem| %>
      <tr>
        <td><%= link_to 'Show', orderitem %></td>
        <td><%= link_to 'Edit', edit_orderitem_path(orderitem) %></td>
        <td><%= link_to 'Destroy', orderitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orderitem', new_orderitem_path %>

app/views/orderitems/new.html.erb
<h1>New Orderitem</h1>

<%= render 'form', orderitem: @orderitem %>

<%= link_to 'Back', orderitems_path %>

app/views/orderitems/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_orderitem_path(@orderitem) %> |
<%= link_to 'Back', orderitems_path %>