config/routes.rb
Rails.application.routes.draw do
 
  
  resources :orders
  resources :orderitems
  resources :carts
  resources :cartitems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :categories do 
      member do
        get :sub
      end
    end
    resources :subcategories do
      
    end
    resources :products do 
      
    end

  end
  root to:"homes#index"

  # put 'admin/products/sub', to:'products#sub'
end

app/models/category.rb
class Category < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :subcategories
    extend FriendlyId
    friendly_id :name, use: :slugged
end

app/controllers/admin/categories_controller.rb
module Admin
    class CategoriesController < ApplicationController
      load_and_authorize_resource
        def index
           @categories= Category.all
        end

         def new
           @category = Category.new
        end

        def create
           @category = Category.new(category_params)
           if @category.save
             flash[:success] = "Category successfully created"
             redirect_to admin_category_path(@category)
           else
             flash[:error] = "Something went wrong"
             render 'new'
            end
        end

        def show
            @category = Category.friendly.find(params[:id])
            @subcategory = Subcategory.new
            @subcategories= @category.subcategories
        end

        def edit
           @category = Category.friendly.find(params[:id])
        end

        def update
            @category = Category.friendly.find(params[:id])
            if @category.update(category_params)
              flash[:success] = "Category successfully updated"
              redirect_to admin_category_path(@category)
            else
              flash[:error] = "Something went wrong"
              render 'new'
            end
        end
        def destroy
            @category = Category.friendly.find(params[:id])
           if @category.destroy
                flash[:success] = 'Category was successfully deleted.'
                redirect_to admin_categories_path
            else
                flash[:error] = 'Something went wrong'
                redirect_to admin_categories_path 
            end

            
        end
        def sub
          @subcategories = Subcategory.where("category_id = ?", params[:id])
          respond_to do |format|
            format.js
            format.html
          end
        end
        private
        def category_params
            params.require(:category).permit(:name,:image)

        end
    end 
end 

app/views/admin/categories/_form.html.erb
<div class="container" style="text-align: middle" %>
<% if user_signed_in? %>
    <%= form_for @category, url: admin_categories_path do |form| %>

        <% if @category.errors.any? %>

          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this article from being saved:</h2>
          <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
       <% end %>
          <p> <%= form.label :name %>
          <%= form.text_field :name %>
          </p>
    <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
    </p>

        <%= form.submit 'Submit' %>
    <% end %>
   
<% else %>
    <h1>Not accessible!</h1>
<% end %>
</div>

app/views/admin/categories/_index.html.erb
<div class="container" >
<table class="table table-hover">
   <tr><thead  class="table-dark"> 
   <th> Name </th>
    <th> Picture </th> </tr>
        </thead>
    <tr>
    <% @categories.each do |category| %>
    
      <td><%= category.name %></td>
      <% if category.image_url %>
       <td><%=link_to image_tag(category.image.url()) %></td>
      <% end %>
        <td><%= link_to 'Show', admin_category_path(category) %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>

</table>
</div>



<br>

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<div class="container" style="text-align: middle">
<%= form_for @category, url: admin_category_path, method: :put do|form| %>
    <p> <%= form.label :name %>
    <%= form.text_field :name %>
    </p>
    <p>
    <%= form.label :image %>
    <%= form.file_field :image %>
    </p>
   
   <%= form.submit 'Submit' %>
<% end %>
</div>
<%= link_to 'Show', admin_category_path(@category) %>
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<%= render 'admin/categories/index' %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid" style="text-align: middle">
    <h1 style="text-align: middle">Displaying the Category</h1>
<table class="table table-striped" data: {turbo: false}>

    <tr><td> Name:</td>
    <td><%=  @category.name  %></td></tr>

     <tr><td> Images :</td>
     <td> 
     <%= image_tag @category.image.url, style:'width:50% ;height:40%' %></td>
    <% if can? :manage, Category%>
    <td><%= link_to 'New Subcategory', new_admin_subcategory_path%></td>
    <td><%= link_to 'Edit', edit_admin_category_path(@category) %> </td>
    <td><%= link_to 'Destroy', admin_category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
</table>
</div>


<h2> All Subcategories </h2>
<div class="container" >
<table class="table table-hover">
   <tr><thead  class="table-dark"> 
   <th> Name </th>
    <th> Picture </th> </tr>
        </thead>
    <tr>
      <% @subcategories.each do |subcategory| %>
    
      <td><%= subcategory.name %></td>
      <% if subcategory.image_url %>

       <td><%= image_tag subcategory.image.url, style:'width:35% ;height:40%' %></td>

      <% end %>
      <% if can? :manage, Category%>
       <td><%= link_to 'New Product', new_admin_product_path %></td>
      <td><a href="/admin/subcategories/<%= subcategory.id %>">Show </a></td>
      <td><a href="/admin/subcategories/<%= subcategory.id %>/edit">Edit </a></td>
      <td><%= link_to 'Destroy', admin_subcategory_path(subcategory.category_id,subcategory.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
     <% end %>
   </tr>
    <% end %>

</table>
</div>


<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/sub.js.erb
$("#subcategories_select").empty().append(`<%= options_from_collection_for_select(@subcategories.all, :id, :name, prompt: true)%>`);